name: repo test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install test dependencies
      run: pip install -r testing/requirements-test.txt
    - name: Build image
      run: docker build . --file Dockerfile --tag testimage:latest
    - name: Start container
      run: docker run -d --name testcontainer -p 8000:8000 testimage:latest
    - name: Wait for container to start
      run: |
        echo "Waiting for container to be ready..."
        timeout_seconds=30
        start_time=$(date +%s)
        while true; do
          current_time=$(date +%s)
          elapsed_time=$((current_time - start_time))
          if [ "$elapsed_time" -ge "$timeout_seconds" ]; then
            echo "Timeout waiting for container."
            exit 1
          fi
          response_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ || true)
          if [ "$response_code" -eq 200 ]; then
            echo "Container is ready!"
            break
          fi
          echo "Container not ready yet (HTTP code: $response_code), sleeping for 2s..."
          sleep 2
        done
    - name: Perform tests
      run: python -m unittest testing.httpCatcherAPI_test
      
